### ISSUE TITLE
intercept term in splines

### ISSUE THREAD

**Issue by hovnatan** [pydata/patsy#108]
I'm trying to understand cubic spline generation. As far as I can see from the output of
```
x = np.linspace(0., 1., 100)
y1 = dmatrix("bs(x, df=6, degree=3, include_intercept=True)", {"x": x})
print(y1)
y2 = dmatrix("bs(x, df=6, degree=3, include_intercept=False)", {"x": x})
print(y2)
```
the `y1` (with intercept) and `y2` (without intercept) are the same. Is there something I am missing? Thanks!

**Comment by njsmith** [comment]
That does look wrong... I just spent a few minutes poking at this and I'm really confused, actually. It looks like there's code and tests that are supposed to handle this, but when I run it interactively I get the same result as you.

**Comment by njsmith** [comment]
OK, I looked again, and AFAICT the answer is actually that they are different, it's just hard to tell by eyeballing :-). Part of what's confusing here is that patsy adjusts the splines to keep the nominal degrees of freedom, so if you say `df=6, include_intercept=False` then it creates a spline with 7 degrees of freedom and then discards one, while if you say `df=6, include_intercept=True` then it creates a spline with 6 degrees of freedom directly -- so either way, the design matrices end up with the same number of dimensions. (This is done partly because it's a reasonable interpretation, and partly because R does it this way and patsy's `bs()` is designed to be numerically compatible with R's `bs()` to facilitate transferring models.)

But at least when I do it, the matrices actually are different, and look like how I'd expect:
```python
In [15]: np.max(y1 - y2)
Out[15]: array(1.0)

In [27]: fig, (ax1, ax2) = plt.subplots(2, 1)
In [28]: ax1.plot(y1)
In [29]: ax2.plot(y2)
```
![plot-output](https://user-images.githubusercontent.com/609896/27255603-f2bb9570-5355-11e7-9d97-0895dc7e890c.png)

Note that both models have the standard constant-valued intercept term in column 0, because you didn't put a `0 +` or `-1` in your formula, but only in the first model does summing all the spline curves (= the remaining columns) together also give you a constant-valued function:
```python
In [32]: np.sum(y1[:, 1:], axis=1)
Out[32]: 
array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [33]: np.sum(y2[:, 1:], axis=1)
Out[33]: 
array([ 0.        ,  0.11638062,  0.22336208,  0.32134012,  0.41071051,
        0.491869  ,  0.56521134,  0.63113329,  0.6900306 ,  0.74229902,
        0.78833432,  0.82853224,  0.86328853,  0.89299896,  0.91805928,
        0.93886524,  0.95581259,  0.96929709,  0.9797145 ,  0.98746057,
        0.99293104,  0.99652169,  0.99862826,  0.9996465 ,  0.99997217,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ])
```

Hope that helps, and if it doesn't match what you're getting then please re-open!
