### ISSUE TITLE
patsy with Aalen Additive Fitter

### ISSUE THREAD

**Issue by ncdingari** [pydata/patsy#109]
I am using `patsy` with `lifelines` python package

When I run
Xtest = patsy.dmatrix('Variable1 + Variable2 -1', data = testData, return_type='dataframe')

Number of rows are being dropped, number of rows in Xtest is less than testData. When we do one-hot-encoding, this won't happen. If I do one-hot-encoding and try to input to
testPred = aaf.predict_survival_function(Xtest.ix[1:10])
is not working

**Comment by njsmith** [comment]
I'm sorry, but from your description I can't tell what you're trying to do, what's happening, or what you expect to happen.

In general, if patsy outputs a matrix that has fewer rows than the input, then this is because it detected that some of the input rows had missing data (`nan` or `None`). See: http://patsy.readthedocs.io/en/latest/API-reference.html#missing-values
