### ISSUE TITLE
Class appears to be a reserved word

### ISSUE THREAD

**Issue by mortonjt** [pydata/patsy#129]
We had some users with qiime2 that had issues with passing in variables with "class" into the formula string.

Is "class" a reserved keyword.  Full discussion is here: https://github.com/qiime2/q2-gneiss/issues/24

**Comment by njsmith** [comment]
That's correct: `class` is a reserved word in Python, and since patsy allows arbitrary Python code inside formulas, Python's regular reserved-word rules apply to formulas too.

The workaround is to use patsy's [quoting operator, `Q`](https://patsy.readthedocs.io/en/latest/builtins-reference.html?highlight=quote#patsy.builtins.Q). Like:

```python
# doesn't work:
dmatrix("age + class", data=...)

# does work:
dmatrix("y ~ age + q('class')", data=...)
```

I suppose we could hack around this by detecting reserved words that can't possibly appear inside an expression (e.g. `class`, `for`, `def`, ...), and "autoquoting" them, but I don't anticipate having time to work on this anytime soon.

**Comment by matthewwardrop** [comment]
Thanks for reporting this @mortonjt ! The workaround above works, and we are not planning new feature development in patsy including changes in this behaviour. In [Formulaic](https://github.com/matthewwardrop/formulaic), the currently in-development successor, this works fine:
```
from formulaic import Formula
Formula('age + class')  # Outputs: 1 + age + class
```
