### ISSUE TITLE
Any way to make patsy safe for code injection?

### ISSUE THREAD

**Issue by FerusAndBeyond** [pydata/patsy#156]
Say I want to send a string from the client and use that in patsy, how could I do this safely? Currently if something like "sys.exit(0)" is part of the formula the app will exit and I reckon all kinds of dangerous stuff can be performed.

**Comment by matthewwardrop** [comment]
This is a really excellent question and observation. I'm not planning to make invasive changes to the evaluation engine in `patsy`, but this issue also affects [Formulaic](https://github.com/matthewwardrop/formulaic), the upcoming successor. I've noted your observations in an existing issue related to this: https://github.com/matthewwardrop/formulaic/issues/17. I'll definitely be putting more thought into this, but the current plan is to add some kind of "safe mode" that disables some useful features in order to make things safer.

**Comment by matthewwardrop** [comment]
Also note that you should be able to pass `eval_env` to `dmatrix` and `dmatrices` to change the evaluation environment, which you can use to exclude `sys` and others from the evaluation namespace. This is true also for formulaic, and indeed by default (except when using `formulaic.model_matrix`) the evaluation environment does not include anything beyond what is included in the incoming data.
