### ISSUE TITLE
Unintuitive patsy crash if "C = " is used elsewhere in the code

### ISSUE THREAD

**Issue by epierson9** [pydata/patsy#174]
Patsy (and libraries that rely on it) crashes if the programmer uses the variable name "C" elsewhere in the code, as shown in the following MWE, with an unintuitive error message:

```
import statsmodels.api as sm
import pandas as pd

d = pd.DataFrame({'a':range(5), 'b':[1, 0, 0, 0, 1]})
sm.OLS.from_formula("b ~ C(a)", data=d).fit()
print("first call works fine")
C = 5
d = pd.DataFrame({'a':range(5), 'b':[1, 0, 0, 0, 1]})
sm.OLS.from_formula("b ~ C(a)", data=d).fit()
print("second call works fine")
```

The first call works fine, but the second call throws an error; eventual error message is

```
patsy.PatsyError: Error evaluating factor: TypeError: 'int' object is not callable
    b ~ C(a)
        ^^^^
```

This is quite hard to debug if the C variable is set far from the patsy call. (In my case, the error came up because I was using sklearn, and C is the name of one of its regularization parameters). Perhaps there's a way to log a more intuitive error message, or to fix this error entirely?

**Comment by matthewwardrop** [comment]
Thanks for getting in touch!

This issue occurs because `patsy` honours the surrounding context when computing formulas. This is convenient because you can define ad hoc functions in the local namespace, and have them be usable in the formula. You can override this behaviour by passing `eval_env` to the `.from_formula` method as described in: `help(sm.OLS.from_formula)` and `help(patsy.dmatrix)`.

I understand that this behaviour could be confusing/annoying at times, since there are ways to work around it, and this project is more-or-less feature-frozen, I'm going to close this one out for now.

**Comment by epierson9** [comment]
thank you for the additional context!
