### ISSUE TITLE
Errors thrown with incr_dbuilders()

### ISSUE THREAD

**Issue by nkconnor** [pydata/patsy#49]
I'm running a logistic regression and having trouble using Patsy's API to prepare the data when it is bigger than a small sample.

Using the ```dmatrices``` function directly on a DataFrame, I am left with this abrupt error ( please note, I spun up an EC2 with 300GB of RAM after encountering this on my laptop, and got the same error ):

    Traceback (most recent call last):
    File "My_File.py", line 22, in <module>
       df, return_type="dataframe")
    File "/root/anaconda/lib/python2.7/site-packages/patsy/highlevel.py", line 297, in dmatrices
     NA_action, return_type)
    File "/root/anaconda/lib/python2.7/site-packages/patsy/highlevel.py", line 156, in do_highlevel_design
    return_type=return_type)
    File "/root/anaconda/lib/python2.7/site-packages/patsy/build.py", line 989, in build_design_matrices
    results.append(builder._build(evaluator_to_values, dtype))
    File "/root/anaconda/lib/python2.7/site-packages/patsy/build.py", line 821, in _build
    m = DesignMatrix(np.empty((num_rows, self.total_columns), dtype=dtype),
    MemoryError

So, I combed through [Patsy's docs](https://patsy.readthedocs.org/en/latest/API-reference.html) and found this gem:

    patsy.incr_dbuilder(formula_like, data_iter_maker, eval_env=0)
        Construct a design matrix builder incrementally from a large data set.

However, the method is sparsely documented, and the source code is largely uncommented.

I have arrived at this code:

    def iter_maker():
        with open("test.tsv", "r") as f:
            reader = csv.DictReader(f, delimiter="\t")
            for row in reader:
                yield(row)
    
    
    y, dta = incr_dbuilders("s ~ C(x) + C(y):C(rgh) + \
    C(z):C(f) + C(r):C(p) + C(q):C(w) + \
    C(zr):C(rt) + C(ff):C(djjj) + C(hh):C(tt) + \
    C(bb):lat + C(jj):lng + C(ee):C(bb) + C(qq):C(uu)",
            iter_maker)
    
    df = dmatrix(dta, {}, 0, "drop", return_type="dataframe")

but I receive ```PatsyError: Error evaluating factor: NameError: name 'ff' is not defined```

This is being thrown because _try_incr_builders (called from dmatrix) is returning None [on line 151 of highlevel.py](https://github.com/pydata/patsy/blob/master/patsy/highlevel.py)

What is the correct way to use these Patsy functions to prepare my data? Any examples or guidance you may have will be helpful.

**Comment by njsmith** [comment]
Hi @nkconnor, sorry I missed this report initially! Better late than never I guess...

In case you haven't figured it out in the mean time: the problem is that you are not passing any data into your call to `dmatrix`. `dta` is an object that knows how to take a chunk of data and turn it into a chunk of design matrix, but you have to actually pass in the chunk of data. (Note that it's unrealistic to expect to get a single `df` object out which contains your entire design matrix -- your whole problem here is that this object would be too big to fit into memory. So patsy can give you slices of it one at a time, but you still have to figure out how to do something useful with those slices.) You need something like
```
for data_chunk in iter_maker():
    dmat_chunk = dmatrix(dta, data_chunk, 0, "drop", return_type="dataframe")
    # ... then do something sensible with dmat_chunk
    # This probably requires having logistic regression code that can process design matrices incrementally
```
Note that this will generally be more efficient if you can arrange for each `data_chunk` to be a sizeable collection set of rows -- there's a fair amount of per-chunk overhead (just in terms of allocating the objects, calling `dmatrix`, etc.), so you want each chunk to be as big as possible while still fitting into memory. (The same applies to the initial call to `incr_dbuilder`.)

Hope that helps! Please re-open if not.
