### ISSUE TITLE
Using `=` instead of `~` in a formula

### ISSUE THREAD

**Issue by joonro** [pydata/patsy#50]
I was wondering if using `~` instead of `=` in a formula string is to be compatible with the R formula syntax, or because using the latter will break something. If it won't break anything, could we optionally use `=` in the place of `~`? 

I know it is not a big deal, but I think a model statement with `=` would look more natural.

**Comment by njsmith** [comment]
Basically it's just copied from R (who copied it from S), yeah, and in R/S it's important to have a special character because that character is the built-in operator that switches on formula parsing mode. That doesn't apply to us. Technically supporting `=` in patsy would be trivial, it wouldn't break anything.

OTOH I do kind of like that `~` emphasizes that this is not actually a numerical equation, like `y = x1 + x2` looks like you're setting `y` to be the sum of `x1` and `x2`, which would be a pretty misleading interpretation?

I've also played around with the idea of using `=` to enable a stricter interpretation mode, that disables automatic intercepts and automatic redundancy removal, since these seem to be sticking points for some people.

Given that `~` works perfectly well, and "there should be one-- and preferably only one --obvious way to do it", and the above, I'm inclined to play it safe and stick with just `~` for now. We can revisit this later if there's demand though...

**Comment by njsmith** [comment]
(Oh, and thanks for the suggestion!)

**Comment by joonro** [comment]
I think what you said makes sense - for actual model it would be `y = b0 + b1x1 + ...`. Since we are only specifying variables (not parameters), using `=` can be confusing. Thanks for the reply!

**Comment by njsmith** [comment]
Yep, exactly :-)
