### ISSUE TITLE
Column names without explicitly creating the design matrix

### ISSUE THREAD

**Issue by quantdaddy** [pydata/patsy#71]
I have a large data set and I want to get the unique column names of the design matrix I'll get by specifying the formula. One way is to explicitly create the design matrix and then look up the column name. However, the design matrix is too large and it gives memory error. Is there a way to access the column names without creating the design matrix? I'm not interested in design matrix per se,

**Comment by njsmith** [comment]
You can use [`incr_dbuilder`](https://patsy.readthedocs.org/en/latest/API-reference.html#patsy.incr_dbuilder) or [`incr_dbuilders`](https://patsy.readthedocs.org/en/latest/API-reference.html#patsy.incr_dbuilders) (depending on whether you want to give it `y` values as well -- it's the same distinction as `dmatrix` versus `dmatrices`). They're design to work with data that's too large to fit into memory, so instead of giving them your data directly, you give them a function that returns an iterable over "chunks" of your data. If your data fits into memory (just the design matrix doesn't), then you could do something simple like:
```
def iter_maker():
    return [my_data_frame]
design_info = incr_dbuilder("a + b + log(x)", iter_maker)
```
and now `design_info` is a [`DesignInfo`](https://patsy.readthedocs.org/en/latest/API-reference.html#patsy.DesignInfo) object with a `column_names` attribute.

If your raw data is too large to fit into memory, you can change `iter_maker` so that it returns an iterable over chunks of your data where each chunk is small enough to fit into memory. Writing a generator is often the easiest way to do this -- something like:
```
def iter_maker():
    CHUNK_SIZE = 1000
    offset = 0
    while offset < total_rows:
        yield fetch_rows_from_database(offset=offset, size=CHUNK_SIZE)
```

I'm not sure what use the column names are without the design matrix... I would be curious to hear what you're going to do with them :-)

Notice that once you have a `DesignInfo`, you can use this to generate individual "slices" of your design matrix, so you can pass it to algorithms that can process design matrix incrementally.
```
chunk_of_design_matrix = dmatrix(design_info, chunk_of_data)
```

(NB: this answer assumes you're using patsy 0.4 or greater; everything is still possible with earlier versions but 0.4.0 simplified things by combining what used to be two different classes into a single `DesignInfo` class, so some details may be different.)

**Comment by quantdaddy** [comment]
Thanks, this function works for my data. However it turns out looking at
column names doesn't give me what I want. This is what I want:
I have a data frame (shown below) with column names a and b. Those are
factor variables which take values "a1", "a2" and "b1", "b2" respectively.
 a                   b
"a1"               "b1"
"a1"                "b2"
"a2"                "b2"
"a1"                "b1"

I'm looking for a new variable defined by the formula "0+a:b"
For the above table, the result would look like
"a1:b1"
"a1:b2"
"a2:b2"
"a1:b1"
Looking at column names won't help since it only gives unique combination.
Do you think there is another way to do this, may be something similar to
what you suggested above?

Thank you so much!

**Comment by njsmith** [comment]
Oh, in that case, I'm not sure, sorry! Not really in patsy's bailiwick, but I'm sure there's some reasonable way to do it using pandas directly. I'd suggest asking on stackoverflow or similar.

**Comment by quantdaddy** [comment]
Ok. Just wondering if there is a way to create a sparse design matrix in
patsy? If I can do that, it'll solve the problem.

**Comment by njsmith** [comment]
There isn't right now, no, sorry! I'd like there to be but haven't had time
to do it. Patches accepted of course, but that is definitely not the
shortest route to solving your problem :-).
