### ISSUE TITLE
Why is patsy returning additional columns when I add a None or NaN value?

### ISSUE THREAD

**Issue by rsgmon** [pydata/patsy#81]
I'm getting strange return when None or Nan values are in a dataset. As seen below instead of just dropping the None row it creates additional columns with 1's and 0's.

```
import numpy as np
import pandas as pd
import patsy as pt

df = pd.DataFrame(np.array([(1,3),(2,6),(4,2),(6,3)]), columns=['y','X'])
In[60]: df
Out[60]: 
   y  X
0  1  3
1  2  6
2  4  2
3  6  3
In[61]: pt.dmatrices('y ~ X', df)
Out[61]: 
(DesignMatrix with shape (4, 1)
   y
   1
   2
   4
   6
   Terms:
     'y' (column 0),
 DesignMatrix with shape (4, 2)
   Intercept  X
           1  3
           1  6
           1  2
           1  3
   Terms:
     'Intercept' (column 0)
     'X' (column 1))
In[62]: df = pd.DataFrame(np.array([(1,3),(2,6),(4,2),(6,None)]), columns=['y','X'])
In[63]: pt.dmatrices('y ~ X', df)
Out[63]: 
(DesignMatrix with shape (3, 4)
   y[1]  y[2]  y[4]  y[6]
      1     0     0     0
      0     1     0     0
      0     0     1     0
   Terms:
     'y' (columns 0:4),
 DesignMatrix with shape (3, 3)
   Intercept  X[T.3]  X[T.6]
           1       1       0
           1       0       1
           1       0       0
   Terms:
     'Intercept' (column 0)
     'X' (columns 1:3)) 
```

Why is patsy returning additional columns when I add a None value?

**Comment by njsmith** [comment]
You can't put `None` into a numeric array, so `numpy` is upgrading your array to an array of arbitrary Python objects:
```
In [7]: np.array([(1,3),(2,6),(4,2),(6,None)]).dtype
Out[7]: dtype('O')
```
when you then convert this to a pandas dataframe, then you end up with both columns having object dtype:
```
In [9]: df["y"].dtype
Out[9]: dtype('O')

In [10]: df["X"].dtype
Out[10]: dtype('O')
```

Because your arrays do not have a numeric type, then patsy assumes that they are not numeric but rather categorical. So it's treating each distinct value as a different category, and then doing categorical coding stuff.

If you want to represent a missing value in a numeric dataset, use `np.nan`:
```
In [12]: df = pd.DataFrame(np.array([(1,3),(2,6),(4,2),(6,np.nan)]), columns=['y','X'])

In [13]: dmatrices("y ~ X", df)
Out[13]: 
(DesignMatrix with shape (3, 1)
   y
   1
   2
   4
   Terms:
     'y' (column 0),
 DesignMatrix with shape (3, 2)
   Intercept  X
           1  3
           1  6
           1  2
   Terms:
     'Intercept' (column 0)
     'X' (column 1))
```

Note that if you use a more standard way of creating a pandas dataframe that doesn't involve passing through a numpy array first, then pandas will automatically convert the Nones into nans for you:
```
In [17]: df = pd.DataFrame(dict(y=[1, 2, 4, 6], X=[3, 6, 2, None]))

In [18]: df
Out[18]: 
    X  y
0   3  1
1   6  2
2   2  4
3 NaN  6
```

Hope that helps! Closing because I think it's answered, but if there's something I'm missing then feel free to re-open.
